#!/usr/bin/python
# -*- coding: utf-8 -*-

#Heuristic: number of stacks that the container has to travel. 

from search import printSolution

def good_heuristic(node, goal):
    distances = {}
    for i in range(0, len(goal.problem)):
        boxes = goal.problem[i].split(',')
        for box in boxes:
            if box != '' and box != 'X':
                distances[box] = i

    for i in range(0, len(node.problem)):
        boxes = node.problem[i].split(',')
        for box in boxes:
            if box != '':
                if box in distances:
                    distances[box] = abs(i - distances[box]) + 1 #calculate h
                else:
                    distances[box] = 0
    
    return sum(distances.values())


if __name__ == "__main__":
    height = int(input()) #maximum height of stack
    start = raw_input() #initial location of the containers
    goal = raw_input() #goal state

    printSolution('a*', height, start, goal, good_heuristic)